from database.db_config import get_oracle_connection

# SQL das tabelas
SQL_CREATE_ECO_ACTIONS = """
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ECO_ACTIONS (
            ID                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            USER_ID           VARCHAR2(50),
            CLASS_NAME        VARCHAR2(50),
            PROBABILITY       NUMBER(5,4),
            ECO_SCORE         NUMBER(5),
            POINTS            NUMBER(10),
            IMAGE_SOURCE      VARCHAR2(50),
            CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN  -- ORA-00955: nome já utilizado
            RAISE;
        END IF;
END;
"""


def init_database():
    """
    Cria automaticamente as tabelas necessárias caso ainda não existam.
    """
    try:
        conn = get_oracle_connection()
        cur = conn.cursor()

        # Criar ECO_ACTIONS (se já existir, ignora)
        cur.execute(SQL_CREATE_ECO_ACTIONS)

        conn.commit()
        cur.close()
        conn.close()

        print("🔵 Banco Oracle verificado: tabelas OK.")

    except Exception as e:
        print("🔴 Erro ao inicializar o banco:", str(e))
